const express = require('express');
const pageController = require('../controllers/pageController');
const recipeController = require('../controllers/recipeController');

const router = express.Router();

router.get('/', pageController.dashboard);
router.get('/projects', pageController.projects);
router.post('/projects', pageController.createProject);
router.get('/recipes', pageController.recipes);
router.get('/recipes/new', recipeController.newRecipeForm);
router.get('/recipes/import', recipeController.importRecipeForm);
router.post('/recipes/import', recipeController.importRecipe);
router.post('/prompts/improve', recipeController.improvePrompt);
router.post('/recipes', recipeController.createRecipe);
router.get('/recipes/:id', recipeController.showRecipe);
router.get('/recipes/:id/export', recipeController.exportRecipe);
router.get('/recipes/:id/export/preview', recipeController.exportRecipePreview);
router.get('/recipes/:id/edit', recipeController.editRecipeForm);
router.post('/recipes/:id', recipeController.updateRecipe);
router.post('/recipes/:id/duplicate', recipeController.duplicateRecipe);
router.post('/recipes/:id/delete', recipeController.deleteRecipe);
router.get('/runs/:id', pageController.runDetail);
router.get('/runs/:id/events', pageController.runEvents);
router.get('/runs/:id/diff', pageController.runDiff);
router.get('/runs/:id/logs', pageController.runLogs);
router.get('/runs/:id/failure-report', pageController.exportFailureReport);
router.post('/runs/:id/pause', pageController.pauseRun);
router.post('/runs/:id/resume', pageController.resumeRun);
router.post('/runs/:id/rollback-last-step', pageController.rollbackLastStep);
router.post('/runs/:id/steps/:stepId/approve', pageController.approveRunStep);
router.post('/runs/:id/steps/:stepId/reject', pageController.rejectRunStep);
router.post('/runs/:id/steps/:stepId/retry', pageController.retryRunStep);
router.post('/runs/:id/steps/:stepId/continue-from', pageController.continueFromStep);
router.post('/runs/:id/steps/:stepId/edit-retry', pageController.editPromptAndRetry);
router.post('/runs/:id/steps/:stepId/skip', pageController.skipRunStep);
router.post('/runs/:id/quota-refill', pageController.setQuotaRefill);
router.post('/runs/:id/steps/:stepId/quality-gate-override', pageController.overrideQualityGate);
router.post('/runs/:id/cancel', pageController.cancelRun);
router.get('/help', pageController.help);
router.get('/settings', pageController.settings);
router.post('/settings', pageController.updateSettings);

module.exports = router;
