const express = require('express');
const pageController = require('../controllers/pageController');
const recipeController = require('../controllers/recipeController');
const apiController = require('../controllers/apiController');

const router = express.Router();

router.post('/api/jobs', apiController.startJob);
router.get('/api/jobs/:id', apiController.getJob);
router.post('/api/jobs/:id/prompts', apiController.addJobPrompt);

router.get('/', pageController.dashboard);
router.post('/run', pageController.quickRun);
router.get('/projects', pageController.projects);
router.get('/projects/resolve-folder', pageController.resolveProjectFolder);
router.get('/projects/browse-folders', pageController.browseProjectFolders);
router.get('/projects/inspect-path', pageController.inspectProjectPath);
router.post('/projects', pageController.createProject);
router.get('/recipes', pageController.recipes);
router.get('/recipes/new', recipeController.newRecipeForm);
router.get('/recipes/import', recipeController.importRecipeForm);
router.post('/recipes/import', recipeController.importRecipe);
router.post('/prompts/improve', recipeController.improvePrompt);
router.post('/recipes', recipeController.createRecipe);
router.get('/recipes/:id', recipeController.showRecipe);
router.get('/recipes/:id/export', recipeController.exportRecipe);
router.get('/recipes/:id/export/preview', recipeController.exportRecipePreview);
router.get('/recipes/:id/edit', recipeController.editRecipeForm);
router.post('/recipes/:id', recipeController.updateRecipe);
router.post('/recipes/:id/run', recipeController.runRecipe);
router.post('/recipes/:id/duplicate', recipeController.duplicateRecipe);
router.post('/recipes/:id/delete', recipeController.deleteRecipe);
router.get('/runs', pageController.runs);
router.get('/runs/:id', pageController.runDetail);
router.get('/runs/:id/events', pageController.runEvents);
router.get('/runs/:id/diff', pageController.runDiff);
router.get('/runs/:id/logs', pageController.runLogs);
router.post('/runs/:id/prompts', pageController.addRunPrompt);
router.post('/runs/:id/logs/clear', pageController.clearRunLogs);
router.get('/runs/:id/failure-report', pageController.exportFailureReport);
router.post('/runs/:id/pause', pageController.pauseRun);
router.post('/runs/:id/resume', pageController.resumeRun);
router.post('/runs/:id/save-recipe', pageController.saveRunRecipe);
router.post('/runs/:id/steps/:stepId/retry', pageController.retryRunStep);
router.post('/runs/:id/steps/:stepId/continue-from', pageController.continueFromStep);
router.post('/runs/:id/steps/:stepId/edit-retry', pageController.editPromptAndRetry);
router.post('/runs/:id/steps/:stepId/skip', pageController.skipRunStep);
router.post('/runs/:id/quota-refill', pageController.setQuotaRefill);
router.post('/runs/:id/cancel', pageController.cancelRun);
router.get('/help', pageController.help);
router.get('/settings', pageController.settings);
router.get('/settings/discover-codex', pageController.discoverCodexSetup);
router.post('/settings', pageController.updateSettings);

module.exports = router;
